function loadcss(a){var f=document.createElement("link");f.rel="stylesheet";f.href=a;document.head.insertBefore(f,document.head.childNodes[document.head.childNodes.length-1].nextSibling)}
jQuery(document).ready(function(a){loadcss("/css/mincss2.css");loadcss("/font-awesome-4.6.3/css/font-awesome.min.css");var f,h=a("#top-navigation"),j=h.outerHeight(),i=h.find("a"),k=i.map(function(){if(!(a(this).attr("href").search("/")>=0)){var c=a(a(this).attr("href"));if(c.length)return c}}),g=a(".section .container").width();a(".triangle").css({"border-left":g/2+"px outset transparent","border-right":g/2+"px outset transparent"});a(window).resize(function(){g=a(".container").width();a(".triangle").css({"border-left":g/
2+"px outset transparent","border-right":g/2+"px outset transparent"})});a("#portfolio-grid").mixitup({onMixStart:function(){a("div.toggleDiv").hide()}});a("#clint-slider").bxSlider({pager:false,minSlides:1,maxSlides:5,moveSlides:2,slideWidth:210,slideMargin:25,prevSelector:a("#client-prev"),nextSelector:a("#client-next"),prevText:'<i class="icon-left-open"></i>',nextText:'<i class="icon-right-open"></i>'});a("input, textarea").placeholder();a(window).scroll(function(){a(this).scrollTop()>100?a(".scrollup").fadeIn():
a(".scrollup").fadeOut();a(this).scrollTop()>130?a(".navbar").addClass("navbar-fixed-top animated fadeInDown"):a(".navbar").removeClass("navbar-fixed-top animated fadeInDown");var c=a(this).scrollTop()+j+10,b=k.map(function(){if(a(this).offset().top<c)return this});b=(b=b[b.length-1])&&b.length?b[0].id:"";if(f!==b){f=b;i.parent().removeClass("active").end().filter("[href=#"+b+"]").parent().addClass("active")}});a(".scrollup").click(function(){a("html, body").animate({scrollTop:0},600);return false});
a(window).load(function(){function c(b){return b.replace(/^\//,"").replace(/(index|default).[a-zA-Z]{3,4}$/,"").replace(/\/$/,"")}a("a[href*=#]").each(function(){if(c(location.pathname)==c(this.pathname)&&location.hostname==this.hostname&&this.hash.replace(/#/,"")){var b=a(this.hash),d=a("[name="+this.hash.slice(1)+"]"),e=b.length?b:d.length?d:false;e&&a(this).click(function(){h.parent().attr("style","height:0px").removeClass("in");a(".navbar .btn-navbar").addClass("collapsed");var l=e.offset().top-
63;a("html, body").animate({scrollTop:l},800);return false})}})});a("#subscribe").click(function(){var c=false,b=/^([a-z0-9_.-]+)@([0-9a-z.-]+).([a-z.]{2,6})$/,d=a("input#nlmail").val().toLowerCase();if(d==""||d==" "||!b.test(d)){a("#err-subscribe").show(500);a("#err-subscribe").delay(4E3);a("#err-subscribe").animate({height:"toggle"},500,function(){});c=true}c===false&&a.ajax({type:"POST",url:"php/newsletter.php",data:{email:a("#nlmail").val()},error:function(){alert("An error occurred")},success:function(e){if(e==
"OK"){a("#success-subscribe").show();a("#nlmail").val("")}else alert("An error occurred")}});return false});a("#send-mail").click(function(){var c=a("input#name").val(),b=false;if(c==""||c==" "){a("#err-name").show(500);a("#err-name").delay(4E3);a("#err-name").animate({height:"toggle"},500,function(){});b=true}c=/^([a-z0-9_.-]+)@([da-z.-]+).([a-z.]{2,6})$/;var d=a("input#email").val().toLowerCase();if(d==""||d==" "||!c.test(d)){a("#err-email").show(500);a("#err-email").delay(4E3);a("#err-email").animate({height:"toggle"},
500,function(){});b=true}c=a("textarea#comment").val();if(c==""||c==" "){a("#err-comment").show(500);a("#err-comment").delay(4E3);a("#err-comment").animate({height:"toggle"},500,function(){});b=true}if(b==false){b=a("#contact-form").serialize();a.ajax({type:"POST",url:a("#contact-form").attr("action"),data:b,timeout:6E3,error:function(){},success:function(e){e=a.parseJSON(e);if(e.success){a("#successSend").show();a("#name").val("");a("#email").val("");a("#comment").val("")}else a("#errorSend").show()}})}return false});
a.fn.showHide=function(c){c=a.extend({speed:1E3,easing:"",changeText:0,showText:"Show",hideText:"Hide"},c);a(this).click(function(){a(".toggleDiv").slideUp(c.speed,c.easing);var b=a(this),d=a(this).attr("rel");a(d).slideToggle(c.speed,c.easing,function(){if(c.changeText==1)a(d).is(":visible")?b.text(c.hideText):b.text(c.showText)});return false})};a("div.toggleDiv").hide();a(".show_hide").showHide({speed:500,changeText:0,showText:"View",hideText:"Close"});jQuery(".thumbnail").one("inview",function(c,
b){b==true?jQuery(this).addClass("animated fadeInDown"):jQuery(this).removeClass("animated fadeInDown")});jQuery(".triangle").bind("inview",function(c,b){b==true?jQuery(this).addClass("animated fadeInDown"):jQuery(this).removeClass("animated fadeInDown")});jQuery("#first-person").bind("inview",function(c,b){b==true?jQuery("#first-person").addClass("animated pulse"):jQuery("#first-person").removeClass("animated pulse")});jQuery("#second-person").bind("inview",function(c,b){b==true?jQuery("#second-person").addClass("animated pulse"):
jQuery("#second-person").removeClass("animated pulse")});jQuery("#third-person").bind("inview",function(c,b){b==true?jQuery("#third-person").addClass("animated pulse"):jQuery("#third-person").removeClass("animated pulse")});jQuery(".price-column, .testimonial").bind("inview",function(c,b){b==true?jQuery(this).addClass("animated fadeInDown"):jQuery(this).removeClass("animated fadeInDown")});jQuery(".contact-form").bind("inview",function(c,b){b==true?jQuery(".contact-form").addClass("animated bounceIn"):
jQuery(".contact-form").removeClass("animated bounceIn")});jQuery(".skills > li > span").one("inview",function(c,b){b==true&&jQuery(this).each(function(){jQuery(this).animate({width:jQuery(this).attr("data-width")},3E3)})})});
